task.spawn(function() 
    loadstring(game:HttpGet("https://pandadevelopment.net/virtual/file/0d9388662a543620"))()
  end)
task.spawn(function() 
    loadstring(game:HttpGet("https://pandadevelopment.net/virtual/file/f0ecd5d6c43c89f2"))()
end)
